### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'get'

### ISSUE THREAD

**Issue by apptechzies** [Kunal-Kumar-Sahoo/PyCowinAPI#1]
I get following error when I use it on AWS server:

Traceback (most recent call last):
  File "cowinNotification.py", line 150, in <module>
    jsonResponse = cowin.get_availability_by_pincode(str(key), listDates[x], 18)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cowin_api/api.py", line 55, in get_availability_by_pincode
    return self.get_availability_by_base(caller='pincode', areas=pin_code,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cowin_api/api.py", line 35, in get_availability_by_base
    curr_result = filter_centers_by_age_limit(self._call_api(url),
  File "/home/ubuntu/.local/lib/python3.8/site-packages/cowin_api/utils.py", line 11, in filter_centers_by_age_limit
    original_centers = centers.get('centers')
AttributeError: 'HTTPError' object has no attribute 'get'

**Comment by Kunal-Kumar-Sahoo** [comment]
Can you mail me the code? I ll see and reply to you asap

**Comment by apptechzies** [comment]
Hi,

Please find attached the code file.

Thanks.

**Comment by Kunal-Kumar-Sahoo** [comment]
Did not find any code. Please mail it to my email id kunal.sahoo2003@gmail.com

**Comment by Kunal-Kumar-Sahoo** [comment]
Hey even tried  to replicate your code and something is wrong that I cannot figure out currently. Just try to pass  all the integer values with strings once. It worked out for me and I'll soon catch up to you with a perfect solution. 
Thanks for cooperation !!!

**Comment by apptechzies** [comment]
Can you share the example method call? I get error when I pass pincode as
integer.

**Comment by Kunal-Kumar-Sahoo** [comment]
Just pass pin code in the string format coz api accepts everything as
string. Even in the code of package I have explicitely kept every parameter
in string datatype due to this reason.

**Comment by apptechzies** [comment]
*Request:*

>>> jsonResponse = cowin.get_availability_by_pincode('110005','10-05-2021')


*Error:*

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/home/ubuntu/.local/lib/python3.8/site-packages/cowin_api/api.py",
line 55, in get_availability_by_pincode

    return self.get_availability_by_base(caller='pincode', areas=pin_code,

  File "/home/ubuntu/.local/lib/python3.8/site-packages/cowin_api/api.py",
line 41, in get_availability_by_base

    results += curr_result['centers']

TypeError: 'HTTPError' object is not subscriptable
